### ISSUE TITLE
Not support Android Studio Ladybug | 2024.2.1 Patch 2

### ISSUE THREAD

**Issue by lgGuo** [FanteCooper/AndroidFlutterAssetCompletion#1]
**You must provide the following information**
- Plugin version number, e.g: 1.0.0
- Android Studio version number, e.g: 2023.3.1

**Choose one of the following options**
- A minimal project that can reproduce the issue and is runnable
- The Android Studio log file. Example for MacOS: Click on Help in the menu bar -> Show Log in Finder, and only send the idea.log file

Please send the content of the above file via <a href="mailto:dantewaretech@gmail.com">Email</a> and include the Issue Title.

**Comment by FanteCooper** [comment]
Version v1.1.0 has been updated to support the Android Studio Ladybug | 2024.2.1 Patch 2.
